import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/providers/theme-provider";
import { ModalProvider } from "@/components/providers/modal-provider";
import SideNav from "@/components/admin/SideNav";
import Header from "@/components/admin/Header";
import HeaderMobile from "@/components/admin/HeaderMobile";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ModalProvider />
          <>
            <div className="w-full flex flex-col md:flex-row">
              <SideNav />
              <div className="flex-grow flex flex-col md:ml-60 sm:border-r sm:border-zinc-700 min-h-screen">
                <Header />
                <HeaderMobile />
                <div className="min-w-full p-4 pb-8 overflow-auto">
                  {children}
                </div>
              </div>
            </div>
          </>
        </ThemeProvider>
      </body>
    </html>
  );
}
