import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ModalProvider } from "@/components/providers/modal-provider";
import Header from "@/components/shared/Header";
import HeaderMobile from "@/components/admin/HeaderMobile";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Old One",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ModalProvider />
          <Toaster />
          <Header />
          <HeaderMobile />
          <div className="container mx-auto py-2 px-4 mt-[70px]">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
